"""
Journal formatting profiles.
Each profile includes:
  - font, font_size, line_spacing, margins        (body text)
  - justify: bool                                  (full justification)
  - first_line_indent: float                       (inches, 0 = none)
  - heading_styles: {level: {font, size, bold, italic, caps, spacing_before, spacing_after, alignment}}
  - columns: 1 or 2
  - list_style: "bullet" | "numbered" | "dash"
  - table_style: "booktabs" | "grid" | "minimal"
  - abstract_max_words, title_case, reference_style, structure, csl_style
"""

JOURNAL_PROFILES = {

    # ── Nature ────────────────────────────────────────────────────────────────
    "nature": {
        "name": "Nature",
        "font": "Arial",
        "font_size": 9,
        "line_spacing": 1.5,
        "margins": "1.5-inch",
        "justify": True,
        "first_line_indent": 0.0,
        "columns": 1,
        "list_style": "bullet",
        "table_style": "minimal",
        "abstract_max_words": 150,
        "title_case": "Title Case",
        "reference_style": "superscript",
        "structure": ["Abstract", "Introduction", "Results", "Discussion", "Methods", "References"],
        "csl_style": "nature",
        "heading_styles": {
            1: {"font": "Arial", "size": 12, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 12, "spacing_after": 6, "alignment": "left"},
            2: {"font": "Arial", "size": 10, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 8,  "spacing_after": 4, "alignment": "left"},
            3: {"font": "Arial", "size": 9,  "bold": False, "italic": True,  "caps": False,
                "spacing_before": 6,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── Science ───────────────────────────────────────────────────────────────
    "science": {
        "name": "Science",
        "font": "Times New Roman",
        "font_size": 10,
        "line_spacing": 2.0,
        "margins": "1-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 1,
        "list_style": "numbered",
        "table_style": "minimal",
        "abstract_max_words": 200,
        "title_case": "Title Case",
        "reference_style": "numbered",
        "structure": ["Abstract", "Introduction", "Results", "Discussion", "Materials and Methods", "References"],
        "csl_style": "science",
        "heading_styles": {
            1: {"font": "Times New Roman", "size": 12, "bold": True,  "italic": False, "caps": True,
                "spacing_before": 12, "spacing_after": 6, "alignment": "center"},
            2: {"font": "Times New Roman", "size": 11, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 8,  "spacing_after": 4, "alignment": "left"},
            3: {"font": "Times New Roman", "size": 10, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 6,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── IEEE ──────────────────────────────────────────────────────────────────
    "ieee": {
        "name": "IEEE",
        "font": "Times New Roman",
        "font_size": 10,
        "line_spacing": 1.0,
        "margins": "1-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 2,
        "list_style": "numbered",
        "table_style": "booktabs",
        "abstract_max_words": 250,
        "title_case": "Title Case",
        "reference_style": "numbered",
        "structure": ["Abstract", "Introduction", "Related Work", "Methodology", "Results", "Discussion", "Conclusion", "References"],
        "csl_style": "ieee",
        "heading_styles": {
            1: {"font": "Times New Roman", "size": 10, "bold": True,  "italic": False, "caps": True,
                "spacing_before": 10, "spacing_after": 4, "alignment": "center"},
            2: {"font": "Times New Roman", "size": 10, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 6,  "spacing_after": 3, "alignment": "left"},
            3: {"font": "Times New Roman", "size": 10, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 4,  "spacing_after": 2, "alignment": "left"},
        },
    },

    # ── ACM ───────────────────────────────────────────────────────────────────
    "acm": {
        "name": "ACM",
        "font": "Linux Libertine",
        "font_size": 10,
        "line_spacing": 1.0,
        "margins": "0.75-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 2,
        "list_style": "bullet",
        "table_style": "booktabs",
        "abstract_max_words": 150,
        "title_case": "Title Case",
        "reference_style": "numbered",
        "structure": ["Abstract", "Introduction", "Related Work", "Methodology", "Evaluation", "Discussion", "Conclusion", "References"],
        "csl_style": "acm-sig-proceedings",
        "heading_styles": {
            1: {"font": "Linux Libertine", "size": 11, "bold": True,  "italic": False, "caps": True,
                "spacing_before": 10, "spacing_after": 4, "alignment": "center"},
            2: {"font": "Linux Libertine", "size": 10, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 7,  "spacing_after": 3, "alignment": "left"},
            3: {"font": "Linux Libertine", "size": 10, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 5,  "spacing_after": 2, "alignment": "left"},
        },
    },

    # ── PLOS ONE ──────────────────────────────────────────────────────────────
    "plos": {
        "name": "PLOS ONE",
        "font": "Arial",
        "font_size": 10,
        "line_spacing": 2.0,
        "margins": "1-inch",
        "justify": False,
        "first_line_indent": 0.0,
        "columns": 1,
        "list_style": "numbered",
        "table_style": "minimal",
        "abstract_max_words": 300,
        "title_case": "Title Case",
        "reference_style": "numbered",
        "structure": ["Abstract", "Introduction", "Materials and Methods", "Results", "Discussion", "Conclusion", "References"],
        "csl_style": "plos",
        "heading_styles": {
            1: {"font": "Arial", "size": 12, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 12, "spacing_after": 6, "alignment": "left"},
            2: {"font": "Arial", "size": 11, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 8,  "spacing_after": 4, "alignment": "left"},
            3: {"font": "Arial", "size": 10, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 6,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── NEJM ──────────────────────────────────────────────────────────────────
    "nejm": {
        "name": "New England Journal of Medicine",
        "font": "Times New Roman",
        "font_size": 11,
        "line_spacing": 2.0,
        "margins": "1.25-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 1,
        "list_style": "numbered",
        "table_style": "grid",
        "abstract_max_words": 250,
        "title_case": "Title Case",
        "reference_style": "numbered",
        "structure": ["Abstract", "Introduction", "Methods", "Results", "Discussion", "References"],
        "csl_style": "vancouver",
        "heading_styles": {
            1: {"font": "Times New Roman", "size": 13, "bold": True,  "italic": False, "caps": True,
                "spacing_before": 14, "spacing_after": 6, "alignment": "left"},
            2: {"font": "Times New Roman", "size": 12, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 10, "spacing_after": 4, "alignment": "left"},
            3: {"font": "Times New Roman", "size": 11, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 7,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── JAMA ──────────────────────────────────────────────────────────────────
    "jama": {
        "name": "JAMA",
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 2.0,
        "margins": "1-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 1,
        "list_style": "numbered",
        "table_style": "grid",
        "abstract_max_words": 300,
        "title_case": "Title Case",
        "reference_style": "numbered",
        "structure": ["Abstract", "Introduction", "Methods", "Results", "Discussion", "Conclusions", "References"],
        "csl_style": "jama",
        "heading_styles": {
            1: {"font": "Times New Roman", "size": 14, "bold": True,  "italic": False, "caps": True,
                "spacing_before": 14, "spacing_after": 6, "alignment": "left"},
            2: {"font": "Times New Roman", "size": 12, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 10, "spacing_after": 4, "alignment": "left"},
            3: {"font": "Times New Roman", "size": 12, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 7,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── BMJ ───────────────────────────────────────────────────────────────────
    "bmj": {
        "name": "BMJ",
        "font": "Arial",
        "font_size": 11,
        "line_spacing": 1.5,
        "margins": "1-inch",
        "justify": True,
        "first_line_indent": 0.0,
        "columns": 1,
        "list_style": "bullet",
        "table_style": "grid",
        "abstract_max_words": 250,
        "title_case": "Title Case",
        "reference_style": "numbered",
        "structure": ["Abstract", "Introduction", "Methods", "Results", "Discussion", "Conclusion", "References"],
        "csl_style": "vancouver",
        "heading_styles": {
            1: {"font": "Arial", "size": 13, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 12, "spacing_after": 6, "alignment": "left"},
            2: {"font": "Arial", "size": 11, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 8,  "spacing_after": 4, "alignment": "left"},
            3: {"font": "Arial", "size": 11, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 6,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── The Lancet ────────────────────────────────────────────────────────────
    "lancet": {
        "name": "The Lancet",
        "font": "Times New Roman",
        "font_size": 11,
        "line_spacing": 2.0,
        "margins": "1.25-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 1,
        "list_style": "bullet",
        "table_style": "grid",
        "abstract_max_words": 200,
        "title_case": "Title Case",
        "reference_style": "numbered",
        "structure": ["Abstract", "Introduction", "Methods", "Results", "Discussion", "Contributors", "References"],
        "csl_style": "the-lancet",
        "heading_styles": {
            1: {"font": "Times New Roman", "size": 13, "bold": True,  "italic": False, "caps": True,
                "spacing_before": 12, "spacing_after": 6, "alignment": "left"},
            2: {"font": "Times New Roman", "size": 12, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 9,  "spacing_after": 4, "alignment": "left"},
            3: {"font": "Times New Roman", "size": 11, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 7,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── Cell ──────────────────────────────────────────────────────────────────
    "cell": {
        "name": "Cell",
        "font": "Arial",
        "font_size": 9,
        "line_spacing": 1.5,
        "margins": "1-inch",
        "justify": True,
        "first_line_indent": 0.0,
        "columns": 2,
        "list_style": "numbered",
        "table_style": "minimal",
        "abstract_max_words": 150,
        "title_case": "Title Case",
        "reference_style": "numbered",
        "structure": ["Abstract", "Introduction", "Results", "Discussion", "STAR Methods", "References"],
        "csl_style": "cell",
        "heading_styles": {
            1: {"font": "Arial", "size": 11, "bold": True,  "italic": False, "caps": True,
                "spacing_before": 12, "spacing_after": 5, "alignment": "left"},
            2: {"font": "Arial", "size": 10, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 8,  "spacing_after": 4, "alignment": "left"},
            3: {"font": "Arial", "size": 9,  "bold": False, "italic": True,  "caps": False,
                "spacing_before": 5,  "spacing_after": 2, "alignment": "left"},
        },
    },

    # ── arXiv ─────────────────────────────────────────────────────────────────
    "arxiv": {
        "name": "arXiv",
        "font": "Computer Modern",
        "font_size": 11,
        "line_spacing": 1.2,
        "margins": "1.25-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 1,
        "list_style": "bullet",
        "table_style": "booktabs",
        "abstract_max_words": 250,
        "title_case": "Title Case",
        "reference_style": "alphabetical",
        "structure": ["Abstract", "Introduction", "Related Work", "Methods", "Experiments", "Results", "Conclusion", "References"],
        "csl_style": "apa",
        "heading_styles": {
            1: {"font": "Computer Modern", "size": 14, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 14, "spacing_after": 6, "alignment": "center"},
            2: {"font": "Computer Modern", "size": 12, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 10, "spacing_after": 4, "alignment": "left"},
            3: {"font": "Computer Modern", "size": 11, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 7,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── Elsevier ──────────────────────────────────────────────────────────────
    "elsevier": {
        "name": "Elsevier",
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 2.0,
        "margins": "1-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 1,
        "list_style": "numbered",
        "table_style": "grid",
        "abstract_max_words": 250,
        "title_case": "Title Case",
        "reference_style": "numbered",
        "structure": ["Abstract", "Introduction", "Methods", "Results", "Discussion", "Conclusion", "References"],
        "csl_style": "elsevier-harvard",
        "heading_styles": {
            1: {"font": "Times New Roman", "size": 14, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 14, "spacing_after": 6, "alignment": "left"},
            2: {"font": "Times New Roman", "size": 12, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 10, "spacing_after": 4, "alignment": "left"},
            3: {"font": "Times New Roman", "size": 12, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 7,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── Springer ──────────────────────────────────────────────────────────────
    "springer": {
        "name": "Springer",
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": "1-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 1,
        "list_style": "numbered",
        "table_style": "grid",
        "abstract_max_words": 250,
        "title_case": "Title Case",
        "reference_style": "numbered",
        "structure": ["Abstract", "Introduction", "Methods", "Results", "Discussion", "Conclusion", "References"],
        "csl_style": "springer-lecture-notes-in-computer-science",
        "heading_styles": {
            1: {"font": "Times New Roman", "size": 14, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 14, "spacing_after": 6, "alignment": "left"},
            2: {"font": "Times New Roman", "size": 12, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 10, "spacing_after": 4, "alignment": "left"},
            3: {"font": "Times New Roman", "size": 12, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 7,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── Wiley ─────────────────────────────────────────────────────────────────
    "wiley": {
        "name": "Wiley",
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 2.0,
        "margins": "1.25-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 1,
        "list_style": "bullet",
        "table_style": "grid",
        "abstract_max_words": 250,
        "title_case": "Title Case",
        "reference_style": "alphabetical",
        "structure": ["Abstract", "Introduction", "Materials and Methods", "Results", "Discussion", "Conclusion", "References"],
        "csl_style": "apa",
        "heading_styles": {
            1: {"font": "Times New Roman", "size": 14, "bold": True,  "italic": False, "caps": True,
                "spacing_before": 14, "spacing_after": 6, "alignment": "left"},
            2: {"font": "Times New Roman", "size": 12, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 10, "spacing_after": 4, "alignment": "left"},
            3: {"font": "Times New Roman", "size": 12, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 7,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── SAGE ──────────────────────────────────────────────────────────────────
    "sage": {
        "name": "SAGE",
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 2.0,
        "margins": "1-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 1,
        "list_style": "numbered",
        "table_style": "grid",
        "abstract_max_words": 200,
        "title_case": "Title Case",
        "reference_style": "alphabetical",
        "structure": ["Abstract", "Introduction", "Methods", "Results", "Discussion", "Conclusion", "References"],
        "csl_style": "sage-harvard",
        "heading_styles": {
            1: {"font": "Times New Roman", "size": 14, "bold": True,  "italic": False, "caps": True,
                "spacing_before": 14, "spacing_after": 6, "alignment": "left"},
            2: {"font": "Times New Roman", "size": 12, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 10, "spacing_after": 4, "alignment": "left"},
            3: {"font": "Times New Roman", "size": 12, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 7,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── Taylor & Francis ──────────────────────────────────────────────────────
    "taylor": {
        "name": "Taylor & Francis",
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 2.0,
        "margins": "1.25-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 1,
        "list_style": "numbered",
        "table_style": "minimal",
        "abstract_max_words": 250,
        "title_case": "Title Case",
        "reference_style": "alphabetical",
        "structure": ["Abstract", "Introduction", "Methods", "Results", "Discussion", "Conclusion", "References"],
        "csl_style": "taylor-and-francis-chicago-author-date",
        "heading_styles": {
            1: {"font": "Times New Roman", "size": 14, "bold": True,  "italic": False, "caps": True,
                "spacing_before": 14, "spacing_after": 6, "alignment": "center"},
            2: {"font": "Times New Roman", "size": 12, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 10, "spacing_after": 4, "alignment": "left"},
            3: {"font": "Times New Roman", "size": 12, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 7,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── Oxford University Press ───────────────────────────────────────────────
    "oxford": {
        "name": "Oxford University Press",
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 2.0,
        "margins": "1-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 1,
        "list_style": "numbered",
        "table_style": "minimal",
        "abstract_max_words": 250,
        "title_case": "Title Case",
        "reference_style": "alphabetical",
        "structure": ["Abstract", "Introduction", "Methods", "Results", "Discussion", "Conclusion", "References"],
        "csl_style": "oxford-university-press-humsoc",
        "heading_styles": {
            1: {"font": "Times New Roman", "size": 14, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 14, "spacing_after": 6, "alignment": "left"},
            2: {"font": "Times New Roman", "size": 13, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 10, "spacing_after": 4, "alignment": "left"},
            3: {"font": "Times New Roman", "size": 12, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 7,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── Cambridge University Press ────────────────────────────────────────────
    "cambridge": {
        "name": "Cambridge University Press",
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 2.0,
        "margins": "1-inch",
        "justify": True,
        "first_line_indent": 0.5,
        "columns": 1,
        "list_style": "bullet",
        "table_style": "minimal",
        "abstract_max_words": 250,
        "title_case": "Title Case",
        "reference_style": "alphabetical",
        "structure": ["Abstract", "Introduction", "Methods", "Results", "Discussion", "Conclusion", "References"],
        "csl_style": "cambridge-university-press-author-date",
        "heading_styles": {
            1: {"font": "Times New Roman", "size": 14, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 14, "spacing_after": 6, "alignment": "left"},
            2: {"font": "Times New Roman", "size": 13, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 10, "spacing_after": 4, "alignment": "left"},
            3: {"font": "Times New Roman", "size": 12, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 7,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── Frontiers ─────────────────────────────────────────────────────────────
    "frontiers": {
        "name": "Frontiers",
        "font": "Arial",
        "font_size": 10,
        "line_spacing": 2.0,
        "margins": "1-inch",
        "justify": False,
        "first_line_indent": 0.0,
        "columns": 1,
        "list_style": "numbered",
        "table_style": "minimal",
        "abstract_max_words": 350,
        "title_case": "Title Case",
        "reference_style": "alphabetical",
        "structure": ["Abstract", "Introduction", "Materials and Methods", "Results", "Discussion", "Conclusion", "Author Contributions", "References"],
        "csl_style": "frontiers",
        "heading_styles": {
            1: {"font": "Arial", "size": 12, "bold": True,  "italic": False, "caps": True,
                "spacing_before": 12, "spacing_after": 6, "alignment": "left"},
            2: {"font": "Arial", "size": 11, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 8,  "spacing_after": 4, "alignment": "left"},
            3: {"font": "Arial", "size": 10, "bold": False, "italic": True,  "caps": False,
                "spacing_before": 6,  "spacing_after": 3, "alignment": "left"},
        },
    },

    # ── PNAS ──────────────────────────────────────────────────────────────────
    "pnas": {
        "name": "PNAS",
        "font": "Arial",
        "font_size": 9,
        "line_spacing": 1.5,
        "margins": "0.75-inch",
        "justify": True,
        "first_line_indent": 0.0,
        "columns": 2,
        "list_style": "numbered",
        "table_style": "booktabs",
        "abstract_max_words": 250,
        "title_case": "Title Case",
        "reference_style": "numbered",
        "structure": ["Abstract", "Introduction", "Results", "Discussion", "Materials and Methods", "References"],
        "csl_style": "pnas",
        "heading_styles": {
            1: {"font": "Arial", "size": 11, "bold": True,  "italic": False, "caps": True,
                "spacing_before": 10, "spacing_after": 4, "alignment": "left"},
            2: {"font": "Arial", "size": 10, "bold": True,  "italic": False, "caps": False,
                "spacing_before": 7,  "spacing_after": 3, "alignment": "left"},
            3: {"font": "Arial", "size": 9,  "bold": False, "italic": True,  "caps": False,
                "spacing_before": 5,  "spacing_after": 2, "alignment": "left"},
        },
    },
}


def get_journal_profile(journal_name: str) -> dict:
    """Return the profile for journal_name (case-insensitive). Returns {} if not found."""
    return JOURNAL_PROFILES.get(journal_name.lower().strip(), {})


def get_journal_list() -> list:
    """Return all journal IDs."""
    return list(JOURNAL_PROFILES.keys())