"""
Predefined journal formatting profiles with specific requirements.
"""

JOURNAL_PROFILES = {
    "nature": {
        "name": "Nature",
        "abstract_max_words": 150,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1.25, "right": 1.25},
        "reference_style": "superscript",
        "keywords": True,
        "max_keywords": 5,
        "structure": ["Title", "Abstract", "Keywords", "Introduction", "Methods", "Results", "Discussion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": 5,
        "supplementary_info": True,
    },
    "science": {
        "name": "Science",
        "abstract_max_words": 200,
        "font": "Courier New",
        "font_size": 11,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "numbered",
        "keywords": False,
        "structure": ["Title", "Abstract", "Introduction", "Methods", "Results", "Discussion", "References"],
        "title_case": "UPPERCASE",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": 6,
        "supplementary_info": True,
    },
    "ieee": {
        "name": "IEEE",
        "abstract_max_words": 100,
        "font": "Times New Roman",
        "font_size": 10,
        "line_spacing": 1.0,
        "margins": {"top": 0.75, "bottom": 0.75, "left": 0.75, "right": 0.75},
        "reference_style": "numbered",
        "keywords": True,
        "max_keywords": 8,
        "structure": ["I. INTRODUCTION", "II. METHODOLOGY", "III. RESULTS", "IV. DISCUSSION", "V. CONCLUSION", "REFERENCES"],
        "title_case": "Title Case",
        "section_format": "roman_numerals",
        "figures_captions_placement": "below",
        "tables_captions_placement": "below",
        "doi_required": False,
        "page_limit": 8,
        "supplementary_info": False,
    },
    "acm": {
        "name": "ACM",
        "abstract_max_words": 150,
        "font": "Times New Roman",
        "font_size": 10,
        "line_spacing": 1.0,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "alphabetical",
        "keywords": True,
        "max_keywords": 10,
        "structure": ["Abstract", "Introduction", "Related Work", "Methodology", "Results", "Discussion", "Conclusion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": 10,
        "supplementary_info": True,
    },
    "arxiv": {
        "name": "arXiv",
        "abstract_max_words": 250,
        "font": "Computer Modern",
        "font_size": 11,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "alphabetical",
        "keywords": True,
        "max_keywords": 0,
        "structure": ["Abstract", "Introduction", "Main Content", "Conclusion", "References"],
        "title_case": "As Written",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": False,
        "page_limit": None,
        "supplementary_info": True,
    },
    "plos": {
        "name": "PLOS ONE",
        "abstract_max_words": 300,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "numbered",
        "keywords": True,
        "max_keywords": 10,
        "structure": ["Abstract", "Introduction", "Materials and Methods", "Results", "Discussion", "Conclusion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": None,
        "supplementary_info": True,
    },
    "cell": {
        "name": "Cell",
        "abstract_max_words": 150,
        "font": "Helvetica",
        "font_size": 9,
        "line_spacing": 1.0,
        "margins": {"top": 0.75, "bottom": 0.75, "left": 0.75, "right": 0.75},
        "reference_style": "superscript",
        "keywords": True,
        "max_keywords": 6,
        "structure": ["Introduction", "Results", "Discussion", "Experimental Procedures", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": 8,
        "supplementary_info": True,
    },
    "lancet": {
        "name": "The Lancet",
        "abstract_max_words": 250,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1.25, "right": 1.25},
        "reference_style": "superscript",
        "keywords": True,
        "max_keywords": 5,
        "structure": ["Summary", "Introduction", "Methods", "Results", "Discussion", "Conclusion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": 6,
        "supplementary_info": True,
    },
    "jama": {
        "name": "JAMA",
        "abstract_max_words": 350,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "superscript",
        "keywords": True,
        "max_keywords": 10,
        "structure": ["Abstract", "Introduction", "Methods", "Results", "Discussion", "Conclusion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": 8,
        "supplementary_info": True,
    },
    "nejm": {
        "name": "New England Journal of Medicine",
        "abstract_max_words": 250,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1.25, "right": 1.25},
        "reference_style": "superscript",
        "keywords": True,
        "max_keywords": 5,
        "structure": ["Abstract", "Introduction", "Methods", "Results", "Discussion", "Conclusions", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": 6,
        "supplementary_info": True,
    },
    "bmj": {
        "name": "British Medical Journal",
        "abstract_max_words": 300,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "superscript",
        "keywords": True,
        "max_keywords": 10,
        "structure": ["Abstract", "Introduction", "Methods", "Results", "Discussion", "Conclusion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": 8,
        "supplementary_info": True,
    },
    "frontiers": {
        "name": "Frontiers in Neuroscience",
        "abstract_max_words": 250,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "numbered",
        "keywords": True,
        "max_keywords": 8,
        "structure": ["Abstract", "Introduction", "Materials and Methods", "Results", "Discussion", "Conclusion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": None,
        "supplementary_info": True,
    },
    "pnas": {
        "name": "Proceedings of the National Academy of Sciences",
        "abstract_max_words": 150,
        "font": "Times New Roman",
        "font_size": 9,
        "line_spacing": 1.0,
        "margins": {"top": 0.75, "bottom": 0.75, "left": 0.75, "right": 0.75},
        "reference_style": "superscript",
        "keywords": True,
        "max_keywords": 5,
        "structure": ["Abstract", "Introduction", "Results", "Discussion", "Materials and Methods", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": 6,
        "supplementary_info": True,
    },
    "elsevier": {
        "name": "Elsevier (General)",
        "abstract_max_words": 200,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "numbered",
        "keywords": True,
        "max_keywords": 6,
        "structure": ["Abstract", "Keywords", "Introduction", "Materials and Methods", "Results", "Discussion", "Conclusion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": None,
        "supplementary_info": True,
    },
    "springer": {
        "name": "Springer Nature",
        "abstract_max_words": 200,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "numbered",
        "keywords": True,
        "max_keywords": 6,
        "structure": ["Abstract", "Keywords", "Introduction", "Materials and Methods", "Results", "Discussion", "Conclusion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": None,
        "supplementary_info": True,
    },
    "wiley": {
        "name": "Wiley",
        "abstract_max_words": 250,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "superscript",
        "keywords": True,
        "max_keywords": 8,
        "structure": ["Abstract", "Keywords", "Introduction", "Results and Discussion", "Conclusion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": None,
        "supplementary_info": True,
    },
    "sage": {
        "name": "SAGE Publications",
        "abstract_max_words": 200,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "superscript",
        "keywords": True,
        "max_keywords": 6,
        "structure": ["Abstract", "Keywords", "Introduction", "Method", "Results", "Discussion", "Conclusion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": None,
        "supplementary_info": True,
    },
    "taylor_francis": {
        "name": "Taylor & Francis",
        "abstract_max_words": 200,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "superscript",
        "keywords": True,
        "max_keywords": 6,
        "structure": ["Abstract", "Keywords", "Introduction", "Methodology", "Results", "Discussion", "Conclusion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": None,
        "supplementary_info": True,
    },
    "oxford": {
        "name": "Oxford University Press",
        "abstract_max_words": 250,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "superscript",
        "keywords": True,
        "max_keywords": 6,
        "structure": ["Abstract", "Keywords", "Introduction", "Methods", "Results", "Discussion", "Conclusion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": None,
        "supplementary_info": True,
    },
    "cambridge": {
        "name": "Cambridge University Press",
        "abstract_max_words": 200,
        "font": "Times New Roman",
        "font_size": 12,
        "line_spacing": 1.5,
        "margins": {"top": 1, "bottom": 1, "left": 1, "right": 1},
        "reference_style": "superscript",
        "keywords": True,
        "max_keywords": 6,
        "structure": ["Abstract", "Keywords", "Introduction", "Materials and Methods", "Results", "Discussion", "Conclusion", "References"],
        "title_case": "Title Case",
        "section_format": "bold",
        "figures_captions_placement": "below",
        "tables_captions_placement": "above",
        "doi_required": True,
        "page_limit": None,
        "supplementary_info": True,
    },
}


def get_journal_list():
    """Get list of available journals."""
    return list(JOURNAL_PROFILES.keys())


def get_journal_profile(journal_name):
    """Get formatting profile for a specific journal."""
    return JOURNAL_PROFILES.get(journal_name.lower())
